# Generated by Django 5.1.6 on 2025-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("stock_quantity", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
